apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
      - name: web-container
        image: nginx:alpine
        ports:
        - containerPort: 80
        # 🚀 AGREGAMOS ESTO: Inyectamos el ConfigMap como Variable de Entorno
        env:
        - name: PROMPT_MESSAGE
          valueFrom:
            configMapKeyRef:
              name: app-messages  # Kustomize se encargará de cambiar este nombre por el que tiene el hash dinámico
              key: MESSAGE
