apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
      - name: web-container
        # 🚀 CAMBIAMOS ESTA IMAGEN POR UNA MODERNA Y ESTABLE:
        image: nginx:alpine
        ports:
        - containerPort: 80
        env:
        - name: PROMPT_MESSAGE
          valueFrom:
            configMapKeyRef:
              name: app-messages
              key: MESSAGE
